spring.datasource.url=jdbc:mysql://localhost:3306/librarydb
spring.datasource.username=library_user
spring.datasource.password=library_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.sql.init.mode=never
spring.h2.console.enabled=false
